/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectDetailsRouteImport } from './routes/project-details'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as FreelancerSubmitWorkRouteImport } from './routes/freelancer.submit-work'
import { Route as FreelancerProfileRouteImport } from './routes/freelancer.profile'
import { Route as FreelancerNftCertificatesRouteImport } from './routes/freelancer.nft-certificates'
import { Route as FreelancerEarningsRouteImport } from './routes/freelancer.earnings'
import { Route as FreelancerDashboardRouteImport } from './routes/freelancer.dashboard'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as ClientApprovalWorkflowRouteImport } from './routes/client.approval-workflow'
import { Route as ProjectsIdChatRouteImport } from './routes/projects.$id.chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDetailsRoute = ProjectDetailsRouteImport.update({
  id: '/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerSubmitWorkRoute = FreelancerSubmitWorkRouteImport.update({
  id: '/freelancer/submit-work',
  path: '/freelancer/submit-work',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerProfileRoute = FreelancerProfileRouteImport.update({
  id: '/freelancer/profile',
  path: '/freelancer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerNftCertificatesRoute =
  FreelancerNftCertificatesRouteImport.update({
    id: '/freelancer/nft-certificates',
    path: '/freelancer/nft-certificates',
    getParentRoute: () => rootRouteImport,
  } as any)
const FreelancerEarningsRoute = FreelancerEarningsRouteImport.update({
  id: '/freelancer/earnings',
  path: '/freelancer/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerDashboardRoute = FreelancerDashboardRouteImport.update({
  id: '/freelancer/dashboard',
  path: '/freelancer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApprovalWorkflowRoute = ClientApprovalWorkflowRouteImport.update({
  id: '/client/approval-workflow',
  path: '/client/approval-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdChatRoute = ProjectsIdChatRouteImport.update({
  id: '/projects/$id/chat',
  path: '/projects/$id/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/messages': typeof MessagesRoute
  '/project-details': typeof ProjectDetailsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/client/approval-workflow': typeof ClientApprovalWorkflowRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/nft-certificates': typeof FreelancerNftCertificatesRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/submit-work': typeof FreelancerSubmitWorkRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$id/chat': typeof ProjectsIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/messages': typeof MessagesRoute
  '/project-details': typeof ProjectDetailsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/client/approval-workflow': typeof ClientApprovalWorkflowRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/nft-certificates': typeof FreelancerNftCertificatesRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/submit-work': typeof FreelancerSubmitWorkRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$id/chat': typeof ProjectsIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/messages': typeof MessagesRoute
  '/project-details': typeof ProjectDetailsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/client/approval-workflow': typeof ClientApprovalWorkflowRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/nft-certificates': typeof FreelancerNftCertificatesRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/submit-work': typeof FreelancerSubmitWorkRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/projects/$id/chat': typeof ProjectsIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/developers'
    | '/messages'
    | '/project-details'
    | '/sitemap.xml'
    | '/client/approval-workflow'
    | '/client/dashboard'
    | '/freelancer/dashboard'
    | '/freelancer/earnings'
    | '/freelancer/nft-certificates'
    | '/freelancer/profile'
    | '/freelancer/submit-work'
    | '/profile/$userId'
    | '/projects/$id/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/developers'
    | '/messages'
    | '/project-details'
    | '/sitemap.xml'
    | '/client/approval-workflow'
    | '/client/dashboard'
    | '/freelancer/dashboard'
    | '/freelancer/earnings'
    | '/freelancer/nft-certificates'
    | '/freelancer/profile'
    | '/freelancer/submit-work'
    | '/profile/$userId'
    | '/projects/$id/chat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/developers'
    | '/messages'
    | '/project-details'
    | '/sitemap.xml'
    | '/client/approval-workflow'
    | '/client/dashboard'
    | '/freelancer/dashboard'
    | '/freelancer/earnings'
    | '/freelancer/nft-certificates'
    | '/freelancer/profile'
    | '/freelancer/submit-work'
    | '/profile/$userId'
    | '/projects/$id/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DevelopersRoute: typeof DevelopersRoute
  MessagesRoute: typeof MessagesRoute
  ProjectDetailsRoute: typeof ProjectDetailsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ClientApprovalWorkflowRoute: typeof ClientApprovalWorkflowRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  FreelancerDashboardRoute: typeof FreelancerDashboardRoute
  FreelancerEarningsRoute: typeof FreelancerEarningsRoute
  FreelancerNftCertificatesRoute: typeof FreelancerNftCertificatesRoute
  FreelancerProfileRoute: typeof FreelancerProfileRoute
  FreelancerSubmitWorkRoute: typeof FreelancerSubmitWorkRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProjectsIdChatRoute: typeof ProjectsIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-details': {
      id: '/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof ProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/submit-work': {
      id: '/freelancer/submit-work'
      path: '/freelancer/submit-work'
      fullPath: '/freelancer/submit-work'
      preLoaderRoute: typeof FreelancerSubmitWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/profile': {
      id: '/freelancer/profile'
      path: '/freelancer/profile'
      fullPath: '/freelancer/profile'
      preLoaderRoute: typeof FreelancerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/nft-certificates': {
      id: '/freelancer/nft-certificates'
      path: '/freelancer/nft-certificates'
      fullPath: '/freelancer/nft-certificates'
      preLoaderRoute: typeof FreelancerNftCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/earnings': {
      id: '/freelancer/earnings'
      path: '/freelancer/earnings'
      fullPath: '/freelancer/earnings'
      preLoaderRoute: typeof FreelancerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/dashboard': {
      id: '/freelancer/dashboard'
      path: '/freelancer/dashboard'
      fullPath: '/freelancer/dashboard'
      preLoaderRoute: typeof FreelancerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/approval-workflow': {
      id: '/client/approval-workflow'
      path: '/client/approval-workflow'
      fullPath: '/client/approval-workflow'
      preLoaderRoute: typeof ClientApprovalWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/chat': {
      id: '/projects/$id/chat'
      path: '/projects/$id/chat'
      fullPath: '/projects/$id/chat'
      preLoaderRoute: typeof ProjectsIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DevelopersRoute: DevelopersRoute,
  MessagesRoute: MessagesRoute,
  ProjectDetailsRoute: ProjectDetailsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ClientApprovalWorkflowRoute: ClientApprovalWorkflowRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  FreelancerDashboardRoute: FreelancerDashboardRoute,
  FreelancerEarningsRoute: FreelancerEarningsRoute,
  FreelancerNftCertificatesRoute: FreelancerNftCertificatesRoute,
  FreelancerProfileRoute: FreelancerProfileRoute,
  FreelancerSubmitWorkRoute: FreelancerSubmitWorkRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProjectsIdChatRoute: ProjectsIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
